import { useEffect, useMemo, useRef, useState, type CSSProperties, type ChangeEvent, type DragEvent, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { getCurrentWebview } from '@tauri-apps/api/webview';
import { open as openDialog, save as saveDialog } from '@tauri-apps/plugin-dialog';
import { revealItemInDir } from '@tauri-apps/plugin-opener';
import logoUrl from './assets/the-shot-card-logo.png';
import './App.css';

type FitMode = 'contain' | 'cover';
type OutputFormat = 'png' | 'jpg' | 'tiff';
type ExportScale = 1 | 2 | 3;
type FontFamilyId = 'sf-mono' | 'courier' | 'din' | 'din-condensed' | 'arial' | 'arial-narrow' | 'verdana' | 'trebuchet' | 'georgia' | 'times' | 'stix' | 'chalkduster';
type FontOption = { label: string; css: string };
const fontOptions: Record<FontFamilyId, FontOption> = {
  'sf-mono': { label: 'SF Mono · teknik', css: 'ui-monospace, SFMono-Regular, Menlo, monospace' },
  courier: { label: 'Courier New · klasik', css: '"Courier New", Courier, monospace' },
  din: { label: 'DIN Alternate · endüstriyel', css: '"DIN Alternate", Arial, sans-serif' },
  arial: { label: 'Arial · nötr', css: 'Arial, sans-serif' },
  times: { label: 'Times New Roman · serif', css: '"Times New Roman", serif' },
  'din-condensed': { label: 'DIN Condensed · dar', css: '"DIN Condensed", Arial, sans-serif' },
  'arial-narrow': { label: 'Arial Narrow · dar', css: '"Arial Narrow", Arial, sans-serif' },
  verdana: { label: 'Verdana · okunaklı', css: 'Verdana, sans-serif' },
  trebuchet: { label: 'Trebuchet MS · humanist', css: '"Trebuchet MS", sans-serif' },
  georgia: { label: 'Georgia · serif', css: 'Georgia, serif' },
  stix: { label: 'STIX General · editorial', css: 'STIXGeneral, serif' },
  chalkduster: { label: 'Chalkduster · display', css: 'Chalkduster, cursive' },
};
type Photo = { id: string; name: string; dataUrl: string; width: number; height: number; size: number; metadata: Metadata; exifAvailable: boolean };
type NativePhoto = Omit<Photo, 'id'>;
type Metadata = { camera: string; lens: string; focal: string; aperture: string; shutter: string; iso: string };
type Settings = { outerMargin: number; topMargin: number; leftMargin: number; rightMargin: number; bottomMargin: number; photoAreaWidth: number; photoAreaHeight: number; infoGap: number; infoBottom: number; fontSize: number; lineHeight: number; zoom: number; offsetX: number; offsetY: number; background: string; textColor: string; borderEnabled: boolean; borderColor: string; borderWidth: number; fitMode: FitMode; cropFocusX: number; cropFocusY: number; fontFamily: FontFamilyId };
type Preset = { id: string; name: string; ratio: string; width: number; height: number };

const presets: Preset[] = [
  { id: '3:4', name: 'Dikey', ratio: '3:4', width: 1080, height: 1440 },
  { id: '4:5', name: 'Dikey', ratio: '4:5', width: 1080, height: 1350 },
  { id: '1:1', name: 'Kare', ratio: '1:1', width: 1080, height: 1080 },
  { id: '1.91:1', name: 'Yatay', ratio: '1.91:1', width: 1080, height: 566 },
  { id: '4.74:1', name: 'Ultra yatay', ratio: '4.74:1', width: 1080, height: 228 },
];
type Language = 'tr' | 'en' | 'de' | 'fr' | 'es' | 'it';
const languageOptions: Record<Language, string> = { en: 'English', tr: 'Türkçe', es: 'Español', de: 'Deutsch', fr: 'Français', it: 'Italiano' };
const baseUi = {
  localProcessing: 'YEREL İŞLEME', reset: 'AYARLARI SIFIRLA', studio: 'YEREL KOMPOZİSYON STÜDYOSU',
  source: 'KAYNAK', addPhoto: 'FOTOĞRAF EKLE', pickOrDrop: 'Sistem penceresinden seç veya buraya bırak', originalResolution: 'ORİJİNAL ÇÖZ.',
  canvas: 'ÇIKTI KANVASI', backgroundRatio: 'Arka plan oranı', final: 'FINAL', custom: 'Özel', userSize: 'kullanıcı ölçüsü', finalCanvas: 'FINAL CANVAS',
  placement: 'YERLEŞİM', contain: 'CONTAIN', coverCrop: 'COVER / CROP', containNote: 'Kırpma yok · oran korunur · boşluklar dengelenir', coverNote: 'İsteğe bağlı kırpma · odak noktası kullanıcı kontrolünde',
  zoom: 'ZOOM', xPosition: 'X KONUMU', yPosition: 'Y KONUMU', cropX: 'CROP X', cropY: 'CROP Y', technical: 'TEKNİK BİLGİ', selectedPhoto: 'Seçili fotoğraf', waitingPhoto: 'Fotoğraf bekleniyor', clear: 'TEMİZLE',
  camera: 'KAMERA GÖVDESİ', lens: 'LENS', focal: 'ODAK (MM)', aperture: 'DİYAFRAM (F)', shutter: 'ENSTANTANE (S)', iso: 'ISO', exifReady: 'EXIF hazır · düğmeye basınca alanlara eklenir.', exifMissing: 'EXIF bulunamazsa alanları elle doldurabilirsin.', fillExif: 'EXIF’TEN DOLDUR',
  spacing: 'BOŞLUKLAR', top: 'ÜST', bottom: 'ALT', left: 'SOL', right: 'SAĞ', photoWidth: 'FOTO. GENİŞLİK', photoHeight: 'FOTO. YÜKSEKLİK', infoGap: 'BİLGİ ARALIĞI', bottomSpace: 'ALT BOŞLUK',
  visualLanguage: 'GÖRSEL DİL', background: 'ARKA PLAN', text: 'METİN', typeface: 'TYPEFACE', thinBorder: 'İNCE KENARLIK', livePreview: 'CANLI ÖNİZLEME / NATIVE EXPORT AYRIMI', workspaceReady: 'Çalışma alanı hazır', ratio: 'ORAN', resolution: 'ÇÖZÜNÜRLÜK', mode: 'MOD',
  startTitle: 'Bir fotoğraf ekleyerek başla', startDescription: 'Fotoğraf kendi oranını korur; seçtiğin nihai canvas içinde contain yöntemiyle dengeli biçimde yerleşir.', choosePhoto: 'FOTOĞRAF SEÇ', photoArea: 'Fotoğraf alanı', technicalArea: 'Teknik bilgi alanı', previewDisclaimer: 'Önizleme ölçeği final export kalitesini etkilemez.',
  queue: 'KUYRUK', emptyQueue: 'Henüz fotoğraf eklenmedi.', format: 'FORMAT', lossless: 'KAYIPSIZ', highQuality: 'YÜKSEK KALİTE', master: 'MASTER', sameLayout: 'TÜMÜNE AYNI YERLEŞİM', batchExport: 'TOPLU EXPORT', working: 'İŞLENİYOR…', export: 'EXPORT ET', showInFinder: 'FİNDER’DA GÖSTER', fit: 'SIĞDIR',
  saveTitle: 'Export konumunu ve dosya adını seç', exportDone: 'Export tamamlandı.', exportFailed: 'Export başarısız.', batchDone: 'dosya sırayla export edildi.', batchFailed: 'Toplu export başarısız.',
  added: 'fotoğraf sıraya eklendi.', listAdded: 'listeye eklendi.', listRemoved: 'listeden silindi.', exifFilled: 'EXIF bilgileri alanlara eklendi.', noExif: 'Bu dosyada okunabilir EXIF bilgisi bulunamadı.', add: '＋ EKLE',
  preset34: 'Dikey', preset45: 'Dikey', preset11: 'Kare', preset191: 'Yatay', preset474: 'Ultra yatay',
} as const;
type UiText = { [K in keyof typeof baseUi]: string };
const translations: Record<Language, UiText> = {
  tr: baseUi,
  en: { ...baseUi, localProcessing: 'LOCAL PROCESSING', reset: 'RESET SETTINGS', studio: 'LOCAL COMPOSITION STUDIO', source: 'SOURCE', addPhoto: 'ADD PHOTO', pickOrDrop: 'Choose from system window or drop here', originalResolution: 'ORIGINAL RES.', canvas: 'OUTPUT CANVAS', backgroundRatio: 'Background ratio', final: 'FINAL', custom: 'Custom', userSize: 'user size', finalCanvas: 'FINAL CANVAS', placement: 'PLACEMENT', coverCrop: 'COVER / CROP', containNote: 'No crop · ratio preserved · whitespace balanced', coverNote: 'Optional crop · focus point under user control', xPosition: 'X POSITION', yPosition: 'Y POSITION', technical: 'TECHNICAL INFO', selectedPhoto: 'Selected photo', waitingPhoto: 'Waiting for photo', clear: 'CLEAR', camera: 'CAMERA BODY', focal: 'FOCAL (MM)', aperture: 'APERTURE (F)', shutter: 'SHUTTER (S)', exifReady: 'EXIF ready · click the button to fill the fields.', exifMissing: 'If EXIF is unavailable, fill the fields manually.', fillExif: 'FILL FROM EXIF', spacing: 'SPACING', top: 'TOP', bottom: 'BOTTOM', left: 'LEFT', right: 'RIGHT', photoWidth: 'PHOTO WIDTH', photoHeight: 'PHOTO HEIGHT', infoGap: 'INFO GAP', bottomSpace: 'BOTTOM SPACE', visualLanguage: 'VISUAL LANGUAGE', background: 'BACKGROUND', text: 'TEXT', thinBorder: 'THIN BORDER', livePreview: 'LIVE PREVIEW / NATIVE EXPORT SEPARATION', workspaceReady: 'Workspace ready', ratio: 'RATIO', resolution: 'RESOLUTION', mode: 'MODE', startTitle: 'Start by adding a photo', startDescription: 'The photo keeps its own ratio and is balanced inside the selected final canvas using contain.', choosePhoto: 'CHOOSE PHOTO', photoArea: 'Photo area', technicalArea: 'Technical info area', previewDisclaimer: 'Preview scale does not affect final export quality.', queue: 'QUEUE', emptyQueue: 'No photos added yet.', format: 'FORMAT', lossless: 'LOSSLESS', highQuality: 'HIGH QUALITY', master: 'MASTER', sameLayout: 'SAME LAYOUT FOR ALL', batchExport: 'BATCH EXPORT', working: 'PROCESSING…', export: 'EXPORT', showInFinder: 'SHOW IN FINDER', fit: 'FIT', saveTitle: 'Choose export location and filename', exportDone: 'Export complete.', exportFailed: 'Export failed.', batchDone: 'files exported in sequence.', batchFailed: 'Batch export failed.', added: 'photo(s) added to the queue.', listAdded: 'added to the list.', listRemoved: 'removed from the list.', exifFilled: 'EXIF data filled into the fields.', noExif: 'No readable EXIF data was found in this file.', add: '＋ ADD', preset34: 'Portrait', preset45: 'Portrait', preset11: 'Square', preset191: 'Landscape', preset474: 'Ultra wide' },
  de: { ...baseUi, localProcessing: 'LOKALE VERARBEITUNG', reset: 'EINSTELLUNGEN ZURÜCKSETZEN', studio: 'LOKALES KOMPOSITIONSSTUDIO', source: 'QUELLE', addPhoto: 'FOTO HINZUFÜGEN', pickOrDrop: 'Im Systemfenster auswählen oder hier ablegen', originalResolution: 'ORIGINALAUFL.', canvas: 'AUSGABECANVAS', backgroundRatio: 'Hintergrundformat', final: 'FINAL', custom: 'Benutzerdefiniert', userSize: 'Benutzergröße', finalCanvas: 'FINALES CANVAS', placement: 'PLATZIERUNG', coverCrop: 'COVER / CROP', containNote: 'Kein Zuschnitt · Verhältnis bleibt erhalten · Leerraum ausgeglichen', coverNote: 'Optionaler Zuschnitt · Fokuspunkt frei steuerbar', xPosition: 'X-POSITION', yPosition: 'Y-POSITION', technical: 'TECHNISCHE DATEN', selectedPhoto: 'Ausgewähltes Foto', waitingPhoto: 'Foto wird erwartet', clear: 'LEEREN', camera: 'KAMERAGEHÄUSE', focal: 'BRENNWEITE (MM)', aperture: 'BLENDE (F)', shutter: 'VERSCHLUSS (S)', exifReady: 'EXIF bereit · per Klick in die Felder übernehmen.', exifMissing: 'Wenn kein EXIF vorhanden ist, Felder manuell ausfüllen.', fillExif: 'AUS EXIF FÜLLEN', spacing: 'ABSTÄNDE', top: 'OBEN', bottom: 'UNTEN', left: 'LINKS', right: 'RECHTS', photoWidth: 'FOTOBREITE', photoHeight: 'FOTOHÖHE', infoGap: 'INFOABSTAND', bottomSpace: 'UNTERER ABSTAND', visualLanguage: 'VISUELLE SPRACHE', background: 'HINTERGRUND', text: 'TEXT', thinBorder: 'DÜNNER RAHMEN', livePreview: 'LIVE-VORSCHAU / NATIVE-EXPORT-TRENNUNG', workspaceReady: 'Arbeitsbereich bereit', ratio: 'FORMAT', resolution: 'AUFLÖSUNG', mode: 'MODUS', startTitle: 'Mit einem Foto beginnen', startDescription: 'Das Foto behält sein Verhältnis und wird mit contain ausgewogen im gewählten Canvas platziert.', choosePhoto: 'FOTO AUSWÄHLEN', photoArea: 'Fotobereich', technicalArea: 'Technische Daten', previewDisclaimer: 'Die Vorschaugröße beeinflusst nicht die Exportqualität.', queue: 'WARTESCHLANGE', emptyQueue: 'Noch keine Fotos hinzugefügt.', format: 'FORMAT', lossless: 'VERLUSTFREI', highQuality: 'HOHE QUALITÄT', master: 'MASTER', sameLayout: 'GLEICHE PLATZIERUNG FÜR ALLE', batchExport: 'STAPEL-EXPORT', working: 'WIRD VERARBEITET…', export: 'EXPORTIEREN', showInFinder: 'IM FINDER ZEIGEN', fit: 'EINPASSEN', saveTitle: 'Exportort und Dateinamen auswählen', exportDone: 'Export abgeschlossen.', exportFailed: 'Export fehlgeschlagen.', batchDone: 'Dateien nacheinander exportiert.', batchFailed: 'Stapel-Export fehlgeschlagen.', added: 'Foto/Fotos zur Warteschlange hinzugefügt.', listAdded: 'zur Liste hinzugefügt.', listRemoved: 'aus der Liste entfernt.', exifFilled: 'EXIF-Daten in die Felder übernommen.', noExif: 'Keine lesbaren EXIF-Daten in dieser Datei gefunden.', add: '＋ HINZUFÜGEN', preset34: 'Hochformat', preset45: 'Hochformat', preset11: 'Quadrat', preset191: 'Querformat', preset474: 'Ultraweit' },
  fr: { ...baseUi, localProcessing: 'TRAITEMENT LOCAL', reset: 'RÉINITIALISER LES RÉGLAGES', studio: 'STUDIO DE COMPOSITION LOCAL', source: 'SOURCE', addPhoto: 'AJOUTER UNE PHOTO', pickOrDrop: 'Choisir dans la fenêtre système ou déposer ici', originalResolution: 'RÉS. ORIGINALE', canvas: 'CANVAS DE SORTIE', backgroundRatio: 'Format du fond', final: 'FINAL', custom: 'Personnalisé', userSize: 'taille utilisateur', finalCanvas: 'CANVAS FINAL', placement: 'PLACEMENT', coverCrop: 'COVER / CROP', containNote: 'Sans recadrage · ratio conservé · espaces équilibrés', coverNote: 'Recadrage optionnel · point focal contrôlé', xPosition: 'POSITION X', yPosition: 'POSITION Y', technical: 'INFOS TECHNIQUES', selectedPhoto: 'Photo sélectionnée', waitingPhoto: 'En attente d’une photo', clear: 'EFFACER', camera: 'BOÎTIER', focal: 'FOCALE (MM)', aperture: 'OUVERTURE (F)', shutter: 'OBTURATION (S)', exifReady: 'EXIF prêt · cliquez pour remplir les champs.', exifMissing: 'Sans EXIF, remplissez les champs manuellement.', fillExif: 'REMPLIR DEPUIS EXIF', spacing: 'ESPACEMENTS', top: 'HAUT', bottom: 'BAS', left: 'GAUCHE', right: 'DROITE', photoWidth: 'LARGEUR PHOTO', photoHeight: 'HAUTEUR PHOTO', infoGap: 'ÉCART INFOS', bottomSpace: 'ESPACE BAS', visualLanguage: 'LANGAGE VISUEL', background: 'FOND', text: 'TEXTE', thinBorder: 'BORDURE FINE', livePreview: 'APERÇU EN DIRECT / SÉPARATION EXPORT NATIF', workspaceReady: 'Espace de travail prêt', ratio: 'RATIO', resolution: 'RÉSOLUTION', mode: 'MODE', startTitle: 'Commencez par ajouter une photo', startDescription: 'La photo conserve son ratio et se place de façon équilibrée dans le canvas choisi avec contain.', choosePhoto: 'CHOISIR UNE PHOTO', photoArea: 'Zone photo', technicalArea: 'Zone infos techniques', previewDisclaimer: 'L’échelle de l’aperçu n’affecte pas la qualité finale.', queue: 'FILE', emptyQueue: 'Aucune photo ajoutée.', format: 'FORMAT', lossless: 'SANS PERTE', highQuality: 'HAUTE QUALITÉ', master: 'MASTER', sameLayout: 'MÊME PLACEMENT POUR TOUS', batchExport: 'EXPORT GROUPÉ', working: 'TRAITEMENT…', export: 'EXPORTER', showInFinder: 'AFFICHER DANS LE FINDER', fit: 'AJUSTER', saveTitle: 'Choisir le dossier et le nom du fichier', exportDone: 'Export terminé.', exportFailed: 'Échec de l’export.', batchDone: 'fichiers exportés dans l’ordre.', batchFailed: 'Échec de l’export groupé.', added: 'photo(s) ajoutée(s) à la file.', listAdded: 'ajouté à la liste.', listRemoved: 'supprimé de la liste.', exifFilled: 'Données EXIF insérées dans les champs.', noExif: 'Aucune donnée EXIF lisible dans ce fichier.', add: '＋ AJOUTER', preset34: 'Portrait', preset45: 'Portrait', preset11: 'Carré', preset191: 'Paysage', preset474: 'Ultra large' },
  es: { ...baseUi, localProcessing: "PROCESAMIENTO LOCAL", reset: "RESTABLECER AJUSTES", studio: "ESTUDIO DE COMPOSICIÓN LOCAL", source: "FUENTE", addPhoto: "AÑADIR FOTO", pickOrDrop: "Elegir en la ventana del sistema o soltar aquí", originalResolution: "RES. ORIGINAL", canvas: "LIENZO DE SALIDA", backgroundRatio: "Relación del fondo", final: "FINAL", custom: "Personalizado", userSize: "tamaño del usuario", finalCanvas: "LIENZO FINAL", placement: "COLOCACIÓN", contain: "CONTAIN", coverCrop: "COVER / RECORTE", containNote: "Sin recorte · proporción conservada · espacios equilibrados", coverNote: "Recorte opcional · punto focal controlado", zoom: "ZOOM", xPosition: "POSICIÓN X", yPosition: "POSICIÓN Y", cropX: "RECORTE X", cropY: "RECORTE Y", technical: "DATOS TÉCNICOS", selectedPhoto: "Foto seleccionada", waitingPhoto: "Esperando una foto", clear: "LIMPIAR", camera: "CUERPO DE CÁMARA", lens: "OBJETIVO", focal: "FOCAL (MM)", aperture: "DIAFRAGMA (F)", shutter: "OBTURACIÓN (S)", iso: "ISO", exifReady: "EXIF listo · haz clic para rellenar los campos.", exifMissing: "Sin EXIF, rellena los campos manualmente.", fillExif: "RELLENAR DESDE EXIF", spacing: "ESPACIOS", top: "ARRIBA", bottom: "ABAJO", left: "IZQUIERDA", right: "DERECHA", photoWidth: "ANCHO DE FOTO", photoHeight: "ALTO DE FOTO", infoGap: "SEPARACIÓN DE INFO", bottomSpace: "ESPACIO INFERIOR", visualLanguage: "LENGUAJE VISUAL", background: "FONDO", text: "TEXTO", typeface: "TIPOGRAFÍA", thinBorder: "BORDE FINO", livePreview: "VISTA PREVIA / EXPORTACIÓN NATIVA", workspaceReady: "Espacio de trabajo listo", ratio: "PROPORCIÓN", resolution: "RESOLUCIÓN", mode: "MODO", startTitle: "Empieza añadiendo una foto", startDescription: "La foto conserva su proporción y se coloca equilibradamente en el lienzo elegido con contain.", choosePhoto: "ELEGIR FOTO", photoArea: "Área de foto", technicalArea: "Área técnica", previewDisclaimer: "La escala de vista previa no afecta a la calidad final.", queue: "COLA", emptyQueue: "Aún no se han añadido fotos.", format: "FORMATO", lossless: "SIN PÉRDIDA", highQuality: "ALTA CALIDAD", master: "MASTER", sameLayout: "MISMA COLOCACIÓN PARA TODAS", batchExport: "EXPORTACIÓN POR LOTES", working: "PROCESANDO…", export: "EXPORTAR", showInFinder: "MOSTRAR EN FINDER", fit: "AJUSTAR", saveTitle: "Elegir carpeta y nombre de archivo", exportDone: "Exportación completada.", exportFailed: "Error en la exportación.", batchDone: "archivos exportados en orden.", batchFailed: "Error en la exportación por lotes.", added: "foto(s) añadida(s) a la cola.", listAdded: "añadido a la lista.", listRemoved: "eliminado de la lista.", exifFilled: "Datos EXIF insertados en los campos.", noExif: "No se encontraron datos EXIF legibles en este archivo.", add: "＋ AÑADIR", preset34: "Vertical", preset45: "Vertical", preset11: "Cuadrado", preset191: "Horizontal", preset474: "Ultraancho" },
  it: { ...baseUi, localProcessing: "ELABORAZIONE LOCALE", reset: "RIPRISTINA IMPOSTAZIONI", studio: "STUDIO DI COMPOSIZIONE LOCALE", source: "SORGENTE", addPhoto: "AGGIUNGI FOTO", pickOrDrop: "Scegli dalla finestra di sistema o trascina qui", originalResolution: "RIS. ORIGINALE", canvas: "TELA DI USCITA", backgroundRatio: "Formato dello sfondo", final: "FINALE", custom: "Personalizzato", userSize: "dimensione personalizzata", finalCanvas: "TELA FINALE", placement: "POSIZIONAMENTO", contain: "CONTAIN", coverCrop: "COVER / RITAGLIO", containNote: "Nessun ritaglio · proporzioni mantenute · spazi equilibrati", coverNote: "Ritaglio opzionale · punto focale controllato", zoom: "ZOOM", xPosition: "POSIZIONE X", yPosition: "POSIZIONE Y", cropX: "RITAGLIO X", cropY: "RITAGLIO Y", technical: "DATI TECNICI", selectedPhoto: "Foto selezionata", waitingPhoto: "In attesa di una foto", clear: "PULISCI", camera: "CORPO MACCHINA", lens: "OBIETTIVO", focal: "FOCALE (MM)", aperture: "DIAFRAMMA (F)", shutter: "OTTURATORE (S)", iso: "ISO", exifReady: "EXIF pronto · fai clic per compilare i campi.", exifMissing: "Senza EXIF, compila i campi manualmente.", fillExif: "COMPILA DA EXIF", spacing: "SPAZIATURE", top: "ALTO", bottom: "BASSO", left: "SINISTRA", right: "DESTRA", photoWidth: "LARGHEZZA FOTO", photoHeight: "ALTEZZA FOTO", infoGap: "SPAZIO INFO", bottomSpace: "SPAZIO INFERIORE", visualLanguage: "LINGUAGGIO VISIVO", background: "SFONDO", text: "TESTO", typeface: "CARATTERE", thinBorder: "BORDO SOTTILE", livePreview: "ANTEPRIMA LIVE / EXPORT NATIVO", workspaceReady: "Area di lavoro pronta", ratio: "RAPPORTO", resolution: "RISOLUZIONE", mode: "MODALITÀ", startTitle: "Inizia aggiungendo una foto", startDescription: "La foto mantiene le sue proporzioni e viene posizionata in modo equilibrato nella tela scelta con contain.", choosePhoto: "SCEGLI FOTO", photoArea: "Area foto", technicalArea: "Area dati tecnici", previewDisclaimer: "La scala dell’anteprima non influisce sulla qualità finale.", queue: "CODA", emptyQueue: "Nessuna foto aggiunta.", format: "FORMATO", lossless: "SENZA PERDITA", highQuality: "ALTA QUALITÀ", master: "MASTER", sameLayout: "STESSO POSIZIONAMENTO PER TUTTE", batchExport: "EXPORT MULTIPLO", working: "IN ELABORAZIONE…", export: "ESPORTA", showInFinder: "MOSTRA NEL FINDER", fit: "ADATTA", saveTitle: "Scegli cartella e nome del file", exportDone: "Export completato.", exportFailed: "Export non riuscito.", batchDone: "file esportati in sequenza.", batchFailed: "Export multiplo non riuscito.", added: "foto aggiunta alla coda.", listAdded: "aggiunto alla lista.", listRemoved: "rimosso dalla lista.", exifFilled: "Dati EXIF inseriti nei campi.", noExif: "Nessun dato EXIF leggibile trovato in questo file.", add: "＋ AGGIUNGI", preset34: "Verticale", preset45: "Verticale", preset11: "Quadrato", preset191: "Orizzontale", preset474: "Ultra-wide" },
};
const emptyMetadata: Metadata = { camera: '', lens: '', focal: '', aperture: '', shutter: '', iso: '' };
const initialSettings: Settings = { outerMargin: 0, topMargin: 120, leftMargin: 44, rightMargin: 44, bottomMargin: 60, photoAreaWidth: 992, photoAreaHeight: 1078, infoGap: 36, infoBottom: 32, fontSize: 30, lineHeight: 36, zoom: 1, offsetX: 0, offsetY: 0, background: '#ffffff', textColor: '#151515', borderEnabled: true, borderColor: '#e6e1d8', borderWidth: 2, fitMode: 'contain', cropFocusX: 0.5, cropFocusY: 0.5 , fontFamily: 'sf-mono' };

function stripFocal(value: string) { return value.trim().replace(/\s*mm$/i, '').replace(/[^0-9.,]/g, ''); }
function stripAperture(value: string) { return value.trim().replace(/^ƒ?f?\s*\/?/i, '').replace(/[^0-9.,]/g, ''); }
function stripShutter(value: string) { return value.trim().replace(/\s*s$/i, '').replace(/[^0-9/.,]/g, ''); }
function stripIso(value: string) { return value.trim().replace(/^iso\s*/i, '').replace(/[^0-9]/gi, ''); }
function buildLines(data: Metadata) { const lines: string[] = []; if (data.camera.trim()) lines.push(data.camera.trim()); if (data.lens.trim()) lines.push(data.lens.trim()); const capture = [stripFocal(data.focal) ? `${stripFocal(data.focal)}mm` : '', stripAperture(data.aperture) ? `ƒ${stripAperture(data.aperture)}` : '', stripShutter(data.shutter) ? `${stripShutter(data.shutter)}s` : '', stripIso(data.iso) ? `ISO${stripIso(data.iso)}` : ''].filter(Boolean); if (capture.length) lines.push(capture.join(' ')); return lines; }
function formatBytes(bytes: number) { return bytes < 1048576 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / 1048576).toFixed(1)} MB`; }
function safeFileName(value: string) { return value.replace(/\.[^/.]+$/, '').replace(/[^a-zA-Z0-9ğüşöçıİĞÜŞÖÇ_-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'kompozisyon'; }
function readPhoto(file: File): Promise<Photo> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error(`${file.name} okunamadı.`)); reader.onload = () => { const dataUrl = String(reader.result); const image = new Image(); image.onerror = () => reject(new Error(`${file.name} görüntü olarak açılamadı.`)); image.onload = () => resolve({ id: `${file.name}-${file.size}-${file.lastModified}-${Math.random()}`, name: file.name, dataUrl, width: image.naturalWidth, height: image.naturalHeight, size: file.size, metadata: { ...emptyMetadata }, exifAvailable: false }); image.src = dataUrl; }; reader.readAsDataURL(file); }); }

function App() {
  const inputRef = useRef<HTMLInputElement>(null);
  const previewStageRef = useRef<HTMLDivElement>(null);
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [metadata, setMetadata] = useState<Record<string, Metadata>>({});
  const [settings, setSettings] = useState<Settings>(initialSettings);
  const [language, setLanguage] = useState<Language>(() => { const saved = localStorage.getItem('ig-language-v2'); return saved === 'en' || saved === 'tr' || saved === 'es' || saved === 'de' || saved === 'fr' || saved === 'it' ? saved : 'en'; });
  const ui = translations[language];
  const presetLabel = (id: string) => ({ '3:4': ui.preset34, '4:5': ui.preset45, '1:1': ui.preset11, '1.91:1': ui.preset191, '4.74:1': ui.preset474 } as Record<string, string>)[id] ?? id;
  const [presetId, setPresetId] = useState('4:5');
  const [customWidth, setCustomWidth] = useState(1080);
  const [customHeight, setCustomHeight] = useState(1350);
  const [outputFormat, setOutputFormat] = useState<OutputFormat>('png');
  const [exportScale, setExportScale] = useState<ExportScale>(2);
  const [sameLayout, setSameLayout] = useState(true);
  const [dragging, setDragging] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [toast, setToast] = useState('');
  const [exportPath, setExportPath] = useState('');
  const toastTimerRef = useRef<number | undefined>(undefined);
  const [toastAutoHide, setToastAutoHide] = useState(false);
  const [cameraChoices, setCameraChoices] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('ig-camera-user-choices-v2') ?? 'null') ?? []; } catch { return []; } });
  const [lensChoices, setLensChoices] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('ig-lens-user-choices-v2') ?? 'null') ?? []; } catch { return []; } });
  const [previewZoom, setPreviewZoom] = useState(1);
  const [previewPan, setPreviewPan] = useState({ x: 0, y: 0 });
  const [stageSize, setStageSize] = useState({ width: 900, height: 520 });
  const [panning, setPanning] = useState(false);
  const panRef = useRef({ active: false, pointerId: -1, startX: 0, startY: 0, originX: 0, originY: 0 });
  useEffect(() => { localStorage.setItem('ig-language-v2', language); }, [language]);
  useEffect(() => { localStorage.setItem('ig-camera-user-choices-v2', JSON.stringify(cameraChoices)); }, [cameraChoices]);
  useEffect(() => { localStorage.setItem('ig-lens-user-choices-v2', JSON.stringify(lensChoices)); }, [lensChoices]);
  const notify = (message: string, path?: string, autoHide = false) => { if (toastTimerRef.current) window.clearTimeout(toastTimerRef.current); setToast(message); setExportPath(path ?? ''); setToastAutoHide(autoHide); if (autoHide) toastTimerRef.current = window.setTimeout(() => { setToast(''); setExportPath(''); setToastAutoHide(false); }, 5000); };
  const openExportFolder = async () => { if (!exportPath) return; try { await revealItemInDir(exportPath); } catch (error) { notify(error instanceof Error ? error.message : 'Finder açılamadı.', exportPath); } };
  const current = photos.find((photo) => photo.id === selectedId) ?? photos[0] ?? null;
  const currentMeta = current ? metadata[current.id] ?? emptyMetadata : emptyMetadata;
  const lines = useMemo(() => buildLines(currentMeta), [currentMeta]);
  const canvas = useMemo(() => { if (presetId === 'custom') return { width: Math.max(320, customWidth), height: Math.max(320, customHeight), ratio: 'Özel' }; const p = presets.find((item) => item.id === presetId) ?? presets[1]; return { width: p.width, height: p.height, ratio: p.ratio }; }, [presetId, customWidth, customHeight]);
  const exportCanvas = { width: canvas.width * exportScale, height: canvas.height * exportScale };
  const isUltraWide = canvas.ratio === '4.74:1';
  const textScale = isUltraWide ? 0.58 : 1;
  const visibleLines = isUltraWide && lines.length ? [lines.join('   ')] : lines;
  const layout = (lineCount: number) => { const infoHeight = Math.max(isUltraWide ? 26 : 86, lineCount * settings.lineHeight * textScale + (isUltraWide ? 6 : 12)); const x = isUltraWide ? 18 : settings.outerMargin + settings.leftMargin; const width = isUltraWide ? Math.max(240, canvas.width - 36) : Math.max(160, Math.min(settings.photoAreaWidth, canvas.width - x - settings.outerMargin - settings.rightMargin)); const y = isUltraWide ? 18 : settings.outerMargin + settings.topMargin; const infoGap = isUltraWide ? 6 : settings.infoGap; const infoBottom = isUltraWide ? 8 : settings.infoBottom; const maxHeight = Math.max(isUltraWide ? 72 : 160, canvas.height - y - infoGap - infoHeight - infoBottom); const height = isUltraWide ? maxHeight : Math.max(160, Math.min(settings.photoAreaHeight, maxHeight)); const infoWidth = isUltraWide ? canvas.width - 36 : Math.max(160, canvas.width - x - settings.outerMargin - settings.rightMargin); return { photoX: x, photoY: y, photoWidth: width, photoHeight: height, infoX: isUltraWide ? 18 : x, infoY: y + height + infoGap, infoWidth, infoHeight }; };
  const geometry = layout(visibleLines.length);
  const scale = Math.max(0.05, Math.min(1, (stageSize.width - 92) / canvas.width, (stageSize.height - 74) / canvas.height)) * previewZoom;
  const previewWidth = canvas.width * scale;
  const previewHeight = canvas.height * scale;
  useEffect(() => { const element = previewStageRef.current; if (!element) return; const update = () => setStageSize({ width: element.clientWidth, height: element.clientHeight }); update(); const observer = new ResizeObserver(update); observer.observe(element); return () => observer.disconnect(); }, []);
  const setSetting = <K extends keyof Settings,>(key: K, value: Settings[K]) => setSettings((old) => ({ ...old, [key]: value }));
  const setMeta = (key: keyof Metadata, value: string) => { if (!current) return; setMetadata((old) => ({ ...old, [current.id]: { ...(old[current.id] ?? emptyMetadata), [key]: value } })); };
  const fillExif = () => { if (!current) return; const exif = current.metadata; setMetadata((old) => ({ ...old, [current.id]: { camera: exif.camera, lens: exif.lens, focal: stripFocal(exif.focal), aperture: stripAperture(exif.aperture), shutter: stripShutter(exif.shutter), iso: stripIso(exif.iso) } })); notify(current.exifAvailable ? ui.exifFilled : ui.noExif, undefined, true); };
  const addChoice = (kind: 'camera' | 'lens') => { if (!current) return; const value = (kind === 'camera' ? currentMeta.camera : currentMeta.lens).trim(); if (!value) return; if (kind === 'camera') setCameraChoices((old) => old.includes(value) ? old : [...old, value]); else setLensChoices((old) => old.includes(value) ? old : [...old, value]); notify(`${value} ${ui.listAdded}`, undefined, true); };
  const removeChoice = (kind: 'camera' | 'lens', value: string) => { if (kind === 'camera') setCameraChoices((old) => old.filter((item) => item !== value)); else setLensChoices((old) => old.filter((item) => item !== value)); if (current && (kind === 'camera' ? currentMeta.camera : currentMeta.lens) === value) setMeta(kind, ''); notify(`${value} ${ui.listRemoved}`, undefined, true); };
  const addLoadedPhotos = (loaded: Photo[]) => {
    if (!loaded.length) return;
    setPhotos((old) => { const next = [...old, ...loaded]; if (!selectedId) setSelectedId(next[0].id); return next; });
    setMetadata((old) => { const next = { ...old }; loaded.forEach((photo) => { next[photo.id] = { ...emptyMetadata }; }); return next; });
    notify(`${loaded.length} ${ui.added}`, undefined, true);
  };
  const acceptFiles = async (list: FileList | File[]) => {
    const files = Array.from(list).filter((file) => file.type.startsWith('image/') || /\.(jpe?g|png|tiff?|webp)$/i.test(file.name));
    if (!files.length) { notify('Yalnızca görsel dosyaları ekleyebilirsin.'); return; }
    try { addLoadedPhotos(await Promise.all(files.map(readPhoto))); }
    catch (error) { notify(error instanceof Error ? error.message : 'Fotoğraf eklenemedi.'); }
  };
  const acceptPaths = async (paths: string[]) => {
    if (!paths.length) return;
    try {
      const imported = await invoke<NativePhoto[]>('read_image_files', { paths });
      const loaded = imported.map((photo) => ({ ...photo, id: `${photo.name}-${photo.size}-${Math.random()}`, metadata: { ...emptyMetadata, ...photo.metadata }, exifAvailable: Boolean(photo.exifAvailable) }));
      addLoadedPhotos(loaded);
    } catch (error) { notify(error instanceof Error ? error.message : 'Dosya içe aktarılamadı.'); }
  };
  const chooseFiles = async () => {
    try {
      const selection = await openDialog({ multiple: true, directory: false, filters: [{ name: 'Görüntüler', extensions: ['jpg', 'jpeg', 'png', 'tif', 'tiff', 'webp'] }] });
      if (selection) await acceptPaths(Array.isArray(selection) ? selection : [selection]);
    } catch { inputRef.current?.click(); }
  };
  useEffect(() => {
    let unlisten: (() => void) | undefined;
    void getCurrentWebview().onDragDropEvent((event) => {
      if (event.payload.type === 'enter' || event.payload.type === 'over') setDragging(true);
      else if (event.payload.type === 'drop') { setDragging(false); void acceptPaths(event.payload.paths); }
      else setDragging(false);
    }).then((stop) => { unlisten = stop; }).catch(() => undefined);
    return () => unlisten?.();
  }, []);
  const removePhoto = (id: string) => { setPhotos((old) => old.filter((photo) => photo.id !== id)); setMetadata((old) => { const next = { ...old }; delete next[id]; return next; }); if (selectedId === id) setSelectedId(photos.find((photo) => photo.id !== id)?.id ?? null); };
  const defaultFileName = (photo: Photo, index?: number) => { const suffix = index === undefined ? '' : ` ${String(index + 1).padStart(2, '0')}`; return `${safeFileName(photo.name)} ${canvas.ratio} canvas${suffix}.${outputFormat}`; };
  const ensureOutputExtension = (value: string) => { const withoutExtension = value.replace(/\.[^/.]+$/, ''); return `${withoutExtension}.${outputFormat}`; };
  const chooseExportPath = async (photo: Photo, index?: number) => { const dir = await invoke<string>('get_default_export_dir'); return saveDialog({ title: ui.saveTitle, defaultPath: `${dir}/${defaultFileName(photo, index)}`, canCreateDirectories: true, filters: [{ name: outputFormat.toUpperCase(), extensions: [outputFormat] }] }); };
  const exportOne = async (photo: Photo, data: Metadata, index?: number, selectedPath?: string) => {
    const rawLines = buildLines(data);
    const itemLines = canvas.ratio === '4.74:1' && rawLines.length ? [rawLines.join('   ')] : rawLines;
    const g = layout(itemLines.length);
    const outputCanvas = { width: canvas.width * exportScale, height: canvas.height * exportScale };
    const dir = await invoke<string>('get_default_export_dir');
    const outputPath = ensureOutputExtension(selectedPath ?? `${dir}/${defaultFileName(photo, index)}`);
    return invoke<string>('export_composite', { request: { imageData: photo.dataUrl, outputPath, outputFormat, canvasWidth: outputCanvas.width, canvasHeight: outputCanvas.height, background: settings.background, textColor: settings.textColor, borderEnabled: settings.borderEnabled, borderColor: settings.borderColor, borderWidth: Math.max(1, Math.round(settings.borderWidth * exportScale)), photoAreaX: Math.round(g.photoX * exportScale), photoAreaY: Math.round(g.photoY * exportScale), photoAreaWidth: Math.round(g.photoWidth * exportScale), photoAreaHeight: Math.round(g.photoHeight * exportScale), infoX: Math.round(g.infoX * exportScale), infoY: Math.round(g.infoY * exportScale), infoWidth: Math.round(g.infoWidth * exportScale), fontSize: Math.round(settings.fontSize * textScale * exportScale), lineHeight: Math.round(settings.lineHeight * textScale * exportScale), lines: itemLines, fontFamily: settings.fontFamily, fitMode: settings.fitMode, cropFocusX: settings.cropFocusX, cropFocusY: settings.cropFocusY, zoom: settings.zoom, offsetX: settings.offsetX * exportScale, offsetY: settings.offsetY * exportScale } });
  };
  const doExport = async () => {
    if (!current || exporting) return;
    const selectedPath = await chooseExportPath(current);
    if (!selectedPath) return;
    setExporting(true);
    try { const path = await exportOne(current, currentMeta, undefined, selectedPath); notify(ui.exportDone, path); }
    catch (error) { notify(error instanceof Error ? error.message : ui.exportFailed); }
    finally { setExporting(false); }
  };
  const doBatchExport = async () => {
    if (!photos.length || exporting) return;
    const firstPath = await chooseExportPath(photos[0], 0);
    if (!firstPath) return;
    setExporting(true);
    try {
      const normalizedFirst = ensureOutputExtension(firstPath);
      const slash = normalizedFirst.lastIndexOf('/');
      const folder = slash >= 0 ? normalizedFirst.slice(0, slash) : await invoke<string>('get_default_export_dir');
      let lastPath = await exportOne(photos[0], metadata[photos[0].id] ?? photos[0].metadata, 0, normalizedFirst);
      for (let i = 1; i < photos.length; i += 1) lastPath = await exportOne(photos[i], metadata[photos[i].id] ?? photos[i].metadata, i, `${folder}/${defaultFileName(photos[i], i)}`);
      notify(`${photos.length} ${ui.batchDone}`, lastPath);
    } catch (error) { notify(error instanceof Error ? error.message : ui.batchFailed); }
    finally { setExporting(false); }
  };
  const imageStyle = (): CSSProperties => {
    if (!current) return {};
    const base = settings.fitMode === 'cover' ? Math.max(geometry.photoWidth / current.width, geometry.photoHeight / current.height) : Math.min(geometry.photoWidth / current.width, geometry.photoHeight / current.height);
    const width = current.width * base * settings.zoom;
    const height = current.height * base * settings.zoom;
    return { left: `${((geometry.photoX + (geometry.photoWidth - width) / 2 + settings.offsetX) / canvas.width) * 100}%`, top: `${((geometry.photoY + (geometry.photoHeight - height) / 2 + settings.offsetY) / canvas.height) * 100}%`, width: `${(width / canvas.width) * 100}%`, height: `${(height / canvas.height) * 100}%` };
  };
  const handlePreviewWheel = (event: ReactWheelEvent<HTMLDivElement>) => { event.preventDefault(); const panGesture = !event.ctrlKey && !event.metaKey && previewZoom > 1.01; if (!panGesture) { setPreviewZoom((value) => Math.max(.6, Math.min(5, Number((value - event.deltaY * 0.01).toFixed(2))))); } else { const wheelScale = event.deltaMode === 1 ? 16 : 1; setPreviewPan((old) => ({ x: Math.max(-2400, Math.min(2400, old.x - event.deltaX * wheelScale)), y: Math.max(-2400, Math.min(2400, old.y - event.deltaY * wheelScale)) })); } };
  const startPan = (event: ReactPointerEvent<HTMLDivElement>) => { const isPhotoTarget = event.target instanceof Element && Boolean(event.target.closest('.composition-image')); if (!current || !isPhotoTarget || (previewZoom <= 1.01 && settings.zoom <= 1.01) || (event.target as HTMLElement).closest('button')) return; panRef.current = { active: true, pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: settings.offsetX, originY: settings.offsetY }; setPanning(true); event.currentTarget.setPointerCapture(event.pointerId); };
  const movePan = (event: ReactPointerEvent<HTMLDivElement>) => { if (!panRef.current.active || panRef.current.pointerId !== event.pointerId) return; const factor = Math.max(scale, 0.05); const dx = (event.clientX - panRef.current.startX) / factor; const dy = (event.clientY - panRef.current.startY) / factor; setSettings((old) => ({ ...old, offsetX: Math.max(-1000, Math.min(1000, panRef.current.originX + dx)), offsetY: Math.max(-1000, Math.min(1000, panRef.current.originY + dy)) })); };
  const endPan = (event: ReactPointerEvent<HTMLDivElement>) => { if (panRef.current.pointerId === event.pointerId) { panRef.current.active = false; setPanning(false); } };
  const onInputChange = (event: ChangeEvent<HTMLInputElement>) => { if (event.target.files) void acceptFiles(event.target.files); event.target.value = ''; };
  const onDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); void acceptFiles(event.dataTransfer.files); };

  return (
    <div className="app-shell">
      <header className="topbar"><div className="brand-lockup"><div className="brand-mark"><img src={logoUrl} alt="" /></div><div><div className="brand-name">THE SHOT CARD</div><div className="brand-subtitle">Instagram posts made easy <span>•</span> v0.6.7</div></div></div><div className="topbar-actions"><span className="local-badge"><span className="status-dot" /> {ui.localProcessing}</span><button className="ghost-button" onClick={() => setSettings(initialSettings)}>{ui.reset}</button><label className="language-select" aria-label="Language"><select value={language} onChange={(event) => setLanguage(event.target.value as Language)}>{Object.entries(languageOptions).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div></header>
      <main className="workspace">
        <aside className="sidebar">
          <section className="panel-section"><div className="section-kicker">01 / {ui.source}</div><div className={`dropzone ${dragging ? 'is-dragging' : ''}`} onClick={() => void chooseFiles()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={onDrop}><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/tiff" multiple hidden onChange={onInputChange} /><div className="upload-icon">＋</div><strong>{ui.addPhoto}</strong><span>{ui.pickOrDrop}</span></div><div className="file-meta-row"><span>JPG / PNG / TIFF / WEBP</span><span>{ui.originalResolution}</span></div></section>
          <section className="panel-section"><div className="section-heading"><div><div className="section-kicker">02 / {ui.canvas}</div><h2>{ui.backgroundRatio}</h2></div><span className="tiny-tag">{ui.final}</span></div><div className="preset-grid">{presets.map((p) => <button key={p.id} className={`preset-card ${presetId === p.id ? 'active' : ''}`} onClick={() => { setPresetId(p.id); if (p.id === '4.74:1') setSetting('fitMode', 'cover'); }}><span>{presetLabel(p.id)}</span><strong>{p.ratio}</strong><small>{p.width} × {p.height}</small></button>)}<button className={`preset-card custom ${presetId === 'custom' ? 'active' : ''}`} onClick={() => setPresetId('custom')}><span>{ui.custom}</span><strong>↗</strong><small>{ui.userSize}</small></button></div>{presetId === 'custom' && <div className="inline-fields"><label>{ui.photoWidth.replace('FOTO. ', '')}<input type="number" value={customWidth} onChange={(event) => setCustomWidth(Number(event.target.value))} /></label><label>{ui.photoHeight.replace('FOTO. ', '')}<input type="number" value={customHeight} onChange={(event) => setCustomHeight(Number(event.target.value))} /></label></div>}<div className="canvas-readout"><span>{ui.finalCanvas}</span><strong>{canvas.width} × {canvas.height} px</strong><em>{canvas.ratio}</em></div></section>
          <section className="panel-section"><div className="section-kicker">03 / {ui.placement}</div><div className="segmented"><button className={settings.fitMode === 'contain' ? 'active' : ''} onClick={() => setSetting('fitMode', 'contain')}>{ui.contain}</button><button className={settings.fitMode === 'cover' ? 'active danger' : ''} onClick={() => setSetting('fitMode', 'cover')}>{ui.coverCrop}</button></div><div className="mode-note">{settings.fitMode === 'contain' ? ui.containNote : ui.coverNote}</div><RangeControl label={ui.zoom} value={settings.zoom} min={.5} max={2} step={.01} suffix="×" onChange={(v) => setSetting('zoom', v)} /><div className="two-range"><RangeControl label={ui.xPosition} value={settings.offsetX} min={-300} max={300} step={1} suffix=" px" onChange={(v) => setSetting('offsetX', v)} /><RangeControl label={ui.yPosition} value={settings.offsetY} min={-300} max={300} step={1} suffix=" px" onChange={(v) => setSetting('offsetY', v)} /></div>{settings.fitMode === 'cover' && <div className="two-range"><RangeControl label={ui.cropX} value={settings.cropFocusX} min={0} max={1} step={.01} suffix="" onChange={(v) => setSetting('cropFocusX', v)} /><RangeControl label={ui.cropY} value={settings.cropFocusY} min={0} max={1} step={.01} suffix="" onChange={(v) => setSetting('cropFocusY', v)} /></div>}</section>
          <section className="panel-section"><div className="section-heading"><div><div className="section-kicker">04 / {ui.technical}</div><h2>{current ? ui.selectedPhoto : ui.waitingPhoto}</h2></div><button className="mini-button" onClick={() => current && setMetadata((old) => ({ ...old, [current.id]: emptyMetadata }))}>{ui.clear}</button></div><div className="metadata-fields"><EditableListField label={ui.camera} placeholder="örn. ILCE–7M4" value={currentMeta.camera} list={cameraChoices} listId="camera-options" addLabel={ui.add} onChange={(v) => setMeta('camera', v)} onAdd={() => addChoice('camera')} onRemove={(item) => removeChoice('camera', item)} /><EditableListField label={ui.lens} placeholder="örn. 24–70mm F2.8 DG DN" value={currentMeta.lens} list={lensChoices} listId="lens-options" addLabel={ui.add} onChange={(v) => setMeta('lens', v)} onAdd={() => addChoice('lens')} onRemove={(item) => removeChoice('lens', item)} /><div className="field-grid"><NumericField label={ui.focal} placeholder="60" value={currentMeta.focal} onChange={(v) => setMeta('focal', v)} /><NumericField label={ui.aperture} placeholder="6.3" value={currentMeta.aperture} onChange={(v) => setMeta('aperture', v)} /></div><div className="field-grid"><NumericField label={ui.shutter} placeholder="1/125" value={currentMeta.shutter} allowSlash onChange={(v) => setMeta('shutter', v)} /><NumericField label="ISO" placeholder="400" value={currentMeta.iso} onChange={(v) => setMeta('iso', v)} /></div></div><div className="exif-actions"><div className="exif-note">{current?.exifAvailable ? ui.exifReady : ui.exifMissing}</div><button className="mini-button" onClick={fillExif} disabled={!current}>{ui.fillExif}</button></div></section>
          <section className="panel-section compact-section"><div className="section-kicker">05 / {ui.spacing}</div><div className="two-range"><NumberControl label={ui.top} value={settings.topMargin} onChange={(v) => setSetting('topMargin', v)} /><NumberControl label={ui.bottom} value={settings.bottomMargin} onChange={(v) => setSetting('bottomMargin', v)} /></div><div className="two-range"><NumberControl label={ui.left} value={settings.leftMargin} onChange={(v) => setSetting('leftMargin', v)} /><NumberControl label={ui.right} value={settings.rightMargin} onChange={(v) => setSetting('rightMargin', v)} /></div><div className="two-range"><NumberControl label={ui.photoWidth} value={settings.photoAreaWidth} onChange={(v) => setSetting('photoAreaWidth', v)} /><NumberControl label={ui.photoHeight} value={settings.photoAreaHeight} onChange={(v) => setSetting('photoAreaHeight', v)} /></div><div className="two-range"><NumberControl label={ui.infoGap} value={settings.infoGap} onChange={(v) => setSetting('infoGap', v)} /><NumberControl label={ui.bottomSpace} value={settings.infoBottom} onChange={(v) => setSetting('infoBottom', v)} /></div></section>
          <section className="panel-section compact-section"><div className="section-kicker">06 / {ui.visualLanguage}</div><div className="color-row"><label>{ui.background} <span className="swatch" style={{ background: settings.background }} /><input type="color" value={settings.background} onChange={(event) => setSetting('background', event.target.value)} /></label><label>{ui.text} <span className="swatch" style={{ background: settings.textColor }} /><input type="color" value={settings.textColor} onChange={(event) => setSetting('textColor', event.target.value)} /></label></div><label className="font-select">{ui.typeface}<select value={settings.fontFamily} onChange={(event) => setSetting('fontFamily', event.target.value as FontFamilyId)}>{Object.entries(fontOptions).map(([id, option]) => <option key={id} value={id}>{option.label}</option>)}</select></label><div className="toggle-row"><span>{ui.thinBorder}</span><button className={`toggle ${settings.borderEnabled ? 'on' : ''}`} onClick={() => setSetting('borderEnabled', !settings.borderEnabled)}><span /></button></div></section>
        </aside>
        <section className="preview-column">
          <div className="preview-header"><div><div className="section-kicker">{ui.livePreview}</div><h1>{current ? current.name : ui.workspaceReady}</h1></div><div className="preview-readouts"><div><span>{ui.ratio}</span><strong>{canvas.ratio}</strong></div><div><span>{ui.resolution}</span><strong>{exportCanvas.width}×{exportCanvas.height}</strong></div><div><span>{ui.mode}</span><strong>{settings.fitMode.toUpperCase()}</strong></div></div></div>
          <div ref={previewStageRef} className={`preview-stage ${panning ? 'is-panning' : ''}`} onWheel={handlePreviewWheel} onPointerDown={startPan} onPointerMove={movePan} onPointerUp={endPan} onPointerCancel={endPan}><div className="preview-toolbar"><button onClick={() => setPreviewZoom((value) => Math.max(.6, Number((value - .1).toFixed(1))))}>−</button><span>{Math.round(previewZoom * 100)}%</span><button onClick={() => setPreviewZoom((value) => Math.min(5, Number((value + .1).toFixed(1))))}>＋</button><button className="fit-preview" onClick={() => { setPreviewZoom(1); setPreviewPan({ x: 0, y: 0 }); }}>{ui.fit}</button></div>
            {current ? (
              <div className="canvas-wrap" style={{ width: previewWidth, height: previewHeight, background: settings.background, transform: `translate(${previewPan.x}px, ${previewPan.y}px)`, transformOrigin: "center center" }}>
                <div className="canvas-guides" style={{ left: `${geometry.photoX / canvas.width * 100}%`, top: `${geometry.photoY / canvas.height * 100}%`, width: `${geometry.photoWidth / canvas.width * 100}%`, height: `${geometry.photoHeight / canvas.height * 100}%` }} />
                <img className={`composition-image ${settings.fitMode}`} src={current.dataUrl} alt="Kompozisyon önizlemesi" draggable={false} onDragStart={(event) => event.preventDefault()} style={imageStyle()} />
                <div className="info-preview" style={{ left: `${geometry.infoX / canvas.width * 100}%`, top: `${geometry.infoY / canvas.height * 100}%`, width: `${geometry.infoWidth / canvas.width * 100}%`, color: settings.textColor, fontFamily: fontOptions[settings.fontFamily].css, fontSize: settings.fontSize * textScale * scale, lineHeight: `${settings.lineHeight * textScale * scale}px` }}>
                  {visibleLines.map((line) => <div key={line}>{line}</div>)}
                </div>
                {settings.borderEnabled && <div className="canvas-border" style={{ borderColor: settings.borderColor, borderWidth: `${Math.max(1, settings.borderWidth * scale)}px` }} />}
              </div>
            ) : (
              <div className="empty-preview">
                <div className="empty-preview-mark">IG</div>
                <h2>{ui.startTitle}</h2>
                <p>{ui.startDescription}</p>
                <button className="primary-button" onClick={() => void chooseFiles()}>{ui.choosePhoto}</button>
              </div>
            )}
          </div>
          <div className="preview-footer"><span><i className="legend-dot gold" /> {ui.photoArea}</span><span><i className="legend-dot gray" /> {ui.technicalArea}</span><span className="preview-disclaimer">{ui.previewDisclaimer}</span></div>
          <div className="bottom-dock"><div className="dock-left"><div className="section-kicker">07 / {ui.queue}</div><div className="queue-list">{photos.length ? photos.map((photo, index) => <button key={photo.id} className={`queue-item ${photo.id === current?.id ? 'active' : ''}`} onClick={() => setSelectedId(photo.id)}><span className="queue-index">{String(index + 1).padStart(2, '0')}</span><img src={photo.dataUrl} alt="" /><span className="queue-name">{photo.name}<small>{photo.width} × {photo.height} · {formatBytes(photo.size)}</small></span><span className="queue-remove" onClick={(event) => { event.stopPropagation(); removePhoto(photo.id); }}>×</span></button>) : <span className="queue-empty">{ui.emptyQueue}</span>}</div></div><div className="dock-actions"><label className="format-select">{ui.resolution}<select value={exportScale} onChange={(event) => setExportScale(Number(event.target.value) as ExportScale)}><option value={1}>1× · {canvas.width}×{canvas.height}</option><option value={2}>2× · {canvas.width * 2}×{canvas.height * 2}</option><option value={3}>3× · {canvas.width * 3}×{canvas.height * 3}</option></select></label><label className="format-select">{ui.format}<select value={outputFormat} onChange={(event) => setOutputFormat(event.target.value as OutputFormat)}><option value="png">PNG · {ui.lossless}</option><option value="jpg">JPG · {ui.highQuality}</option><option value="tiff">TIFF · {ui.master}</option></select></label><label className="batch-toggle"><input type="checkbox" checked={sameLayout} onChange={(event) => setSameLayout(event.target.checked)} /> {ui.sameLayout}</label><button className="secondary-button" onClick={doBatchExport} disabled={!photos.length || exporting}>{ui.batchExport}</button><button className="primary-button export-button" onClick={doExport} disabled={!current || exporting}>{exporting ? ui.working : ui.export} <span>↗</span></button></div></div>
        </section>
      </main>
      {toast && <div className={`toast ${toastAutoHide ? 'toast-autohide' : ''}`}><div className="toast-copy"><strong>{toast}</strong>{exportPath && <code className="toast-path">{exportPath}</code>}{exportPath && <button className="toast-open" onClick={openExportFolder}>{ui.showInFinder}</button>}</div><button className="toast-close" onClick={() => { setToast(''); setExportPath(''); setToastAutoHide(false); }}>×</button></div>}
    </div>
  );
}

function RangeControl({ label, value, min, max, step, suffix, onChange }: { label: string; value: number; min: number; max: number; step: number; suffix: string; onChange: (value: number) => void }) { return <label className="range-control"><span>{label}<b>{value.toFixed(step < 1 ? 2 : 0)}{suffix}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function NumberControl({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="number-control"><span>{label}</span><input type="number" value={value} min={0} onChange={(event) => onChange(Number(event.target.value))} /><em>px</em></label>; }
function NumericField({ label, placeholder, value, onChange, allowSlash = false }: { label: string; placeholder: string; value: string; onChange: (value: string) => void; allowSlash?: boolean }) {
  return <label className="text-field numeric-field"><span>{label}</span><input inputMode="decimal" value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value.replace(allowSlash ? /[^0-9.,\/]/g : /[^0-9.,]/g, ''))} /></label>;
}
function EditableListField({ label, placeholder, value, list, listId, addLabel, onChange, onAdd, onRemove }: { label: string; placeholder: string; value: string; list: string[]; listId: string; addLabel: string; onChange: (value: string) => void; onAdd: () => void; onRemove: (value: string) => void }) {
  return <label className="text-field editable-list-field"><span>{label}<button type="button" className="mini-button list-add" onClick={onAdd}>{addLabel}</button></span><input list={listId} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /><datalist id={listId}>{list.map((item) => <option key={item} value={item} />)}</datalist>{list.length > 0 && <div className="choice-list">{list.map((item) => <span className="choice-chip" key={item}><button type="button" className="choice-value" onClick={() => onChange(item)}>{item}</button><button type="button" className="choice-remove" aria-label={`${item} sil`} onClick={() => onRemove(item)}>×</button></span>)}</div>}</label>;
}
export default App;
